version: '3.8'

services:
  db:
    image: postgres:15
    container_name: library_db
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Europe/Kyiv
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: